version: "3.8"
#
# Author:  Butch Clark (butch.clark@hushmail.com)
#
services:
  execution-client:
    image: ethereum/client-go:stable
    #pull_policy: always
    container_name: execution-client
    ports:
      - 30303:30303
      - 30303:30303/udp
      - 8545:8545
      - 8546:8546
      - 8551:8551
      - 6060:6060
    volumes:
      - ${EXECUTIONDIR:-/data/geth}:/root/.ethereum
    healthcheck:
      test: [ "CMD-SHELL", "geth attach --exec eth.blockNumber" ]
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      - --http
      - --http.api=eth,net,web3,engine,admin
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --ws
      - --ws.origins=*
      - --ws.addr=0.0.0.0
      - --ws.api=eth,net,web3
      - --authrpc.addr=0.0.0.0
      - --authrpc.vhosts=*
      - --authrpc.jwtsecret=/root/.ethereum/jwt.hex
      - --authrpc.port=8551
      - --txlookuplimit=0
      - --syncmode=snap
      - --metrics
      - --metrics.addr=0.0.0.0
      - --metrics.port=6060
#      - --goerli
#    logging:
#      driver: json-file
#      options:
#        max-size: 2m
#        max-file: 10

  consensus-client:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain
#    pull_policy: always
    container_name: consensus-client
    volumes:
      - ${CONSENSUSDIR:-/data/prysm}:/data
      - ${EXECUTIONDIR:-/data/geth}:/geth
    depends_on:
      execution-client:
        condition: service_healthy
    ports:
      - 4000:4000
      - 3500:3500
    command:
      - --accept-terms-of-use
      - --datadir=/data
      - --disable-monitoring
      - --rpc-host=0.0.0.0
      - --execution-endpoint=http://execution-client:8551
      - --jwt-secret=/geth/jwt.hex
      - --rpc-host=0.0.0.0
      - --rpc-port=4000
      - --grpc-gateway-corsdomain=*
      - --grpc-gateway-host=0.0.0.0
      - --grpc-gateway-port=3500
#      - --prater

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ${PROMETHEUSDIR}:/etc/prometheus
    ports:
      - "9090:9090"
    command: --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - ${GRAFANADIR}:/var/lib/grafana
      - ${GRAFANADIR}/etc/grafana:/etc/grafana